"""
Revision: 07586b6a02e2 - scheduling optional patient (2025-05-11 18:23:31.492832)
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "07586b6a02e2"
down_revision: Union[str, None] = "916735e0356e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "scheduling", "patient_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "scheduling", "sensitive_patient", existing_type=sa.BOOLEAN(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "scheduling", "patient_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "scheduling", "sensitive_patient", existing_type=sa.BOOLEAN(), nullable=False
    )
    # ### end Alembic commands ###
