"""
Revision: 2616e3bb9b4f - create config (2025-05-20 13:55:55.060083)
"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from common.model.column_types.point import Point


revision: str = "2616e3bb9b4f"
down_revision: Union[str, None] = "a760bceaff05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    table = op.create_table(
        "config",
        sa.Column("department_name", sa.String(), nullable=True),
        sa.Column("body_name", sa.String(), nullable=True),
        sa.Column("eplison", sa.Float(), nullable=True),
        sa.Column("minpts", sa.Integer(), nullable=True),
        sa.Column("distance_matrix_api_key", sa.String(), nullable=True),
        sa.Column("departure_coordinates", Point(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.bulk_insert(
        table=table,
        rows=[
            {
                "id": 1,
                "department_name": "",
                "body_name": "",
                "eplison": 0.0,
                "minpts": 0,
                "distance_matrix_api_key": "",
                "created_at": datetime.now(),
                "updated_at": datetime.now(),
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("config")
    # ### end Alembic commands ###
