"""
Revision: 28d47d520121 - create vehicle (2025-04-28 21:05:20.446212)
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "28d47d520121"
down_revision: Union[str, None] = "e9b2f7128fd4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicle",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("license_plate", sa.String(length=7), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("default_driver_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False, default=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["default_driver_id"], ["driver.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vehicle")
    # ### end Alembic commands ###
