"""
Revision: 916735e0356e - create scheduling (2025-05-05 19:52:31.969314)
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "916735e0356e"
down_revision: Union[str, None] = "fb0dc839e85c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduling",
        sa.Column("datetime", sa.DateTime(), nullable=False),
        sa.Column("average_duration", sa.Time(), nullable=False),
        sa.Column("sensitive_patient", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("purpose_id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["location_id"], ["location.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["patient_id"], ["patient.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["purpose_id"], ["purpose.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "companion",
        sa.Column("scheduling_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("cpf", sa.String(length=11), nullable=True),
        sa.Column("phone", sa.String(length=11), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scheduling_id"], ["scheduling.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("companion")
    op.drop_table("scheduling")
    # ### end Alembic commands ###
