"""
Revision: 971fe0d9faa2 - create user (2025-04-26 18:11:37.275911)
"""

from datetime import datetime
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from common.utils.md5 import Md5Utils

revision: str = "971fe0d9faa2"
down_revision: Union[str, None] = "d63e2ebc40fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    table = op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("user_name", sa.String(), nullable=False),
        sa.Column("password", sa.String(length=32), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_name"),
    )
    op.bulk_insert(
        table=table,
        rows=[
            {
                "name": "Administrador",
                "user_name": "admin",
                "password": Md5Utils.md5("admin"),
                "active": True,
                "created_at": datetime.now(),
                "updated_at": datetime.now(),
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
