"""
Revision: a760bceaff05 - create roadmap (2025-05-13 18:58:31.935502)
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "a760bceaff05"
down_revision: Union[str, None] = "07586b6a02e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roadmap",
        sa.Column("driver_id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("departure", sa.DateTime(), nullable=False),
        sa.Column("arrival", sa.DateTime(), nullable=False),
        sa.Column("creation_user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["creation_user_id"], ["user.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["driver_id"], ["driver.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicle.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("scheduling", sa.Column("roadmap_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "scheduling", "roadmap", ["roadmap_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "scheduling", type_="foreignkey")
    op.drop_column("scheduling", "roadmap_id")
    op.drop_table("roadmap")
    # ### end Alembic commands ###
