"""
Revision: fb0dc839e85c - create location (2025-04-29 00:14:37.018187)
"""

import sys
from pathlib import Path

project_root = str(Path(__file__).parent.parent.parent)
sys.path.insert(0, project_root)

from typing import Sequence, Union  # noqa: E402

import sqlalchemy as sa  # noqa: E402
from alembic import op  # noqa: E402

from common.model.column_types.point import Point  # noqa: E402

revision: str = "fb0dc839e85c"
down_revision: Union[str, None] = "dc9eb7169665"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("coordinates", Point(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("location")
    # ### end Alembic commands ###
